version: 1
disable_existing_loggers: false

formatters:
  default:
    format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S"

  audit:
    format: "%(asctime)s - [AUDIT] - %(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S"

handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: default
    stream: ext://sys.stdout

  file:
    class: logging.handlers.TimedRotatingFileHandler
    level: DEBUG
    formatter: default
    filename: logs/soulbuddy.log
    when: midnight
    backupCount: 7
    encoding: utf-8

  audit_file:
    class: logging.handlers.TimedRotatingFileHandler
    level: INFO
    formatter: audit
    filename: logs/audit.log
    when: midnight
    backupCount: 30
    encoding: utf-8

root:
  level: DEBUG
  handlers: [console, file]

loggers:
  audit:
    level: INFO
    handlers: [audit_file]
    propagate: false

  urllib3:
    level: WARNING

  asyncio:
    level: WARNING

  langchain:
    level: INFO
